# This is an example of how to run the backend in production using the image
# from GitHub Packages and a volume mount for data.

name: cals-cals

services:
    server:
        image: 'ghcr.io/olillin/cals-cals:latest'
        container_name: cals-cals-server
        restart: always
        volumes:
            - ./data:/app/data

        ports:
            - '3000:3000'
