# This compose file builds and runs the backend locally for development.

name: cals-cals-dev

services:
    server:
        build:
            context: .
        restart: unless-stopped
        environment:
            REDIS_URL: redis://redis:6379
            NODE_ENV: development
        volumes:
            - ./data:/app/data

        ports:
            - '3000:3000'

        depends_on:
            - redis
    redis:
        image: redis:8.6-alpine
        restart: unless-stopped
        ports:
            - '6379:6379'
