import type { Metadata, Viewport } from 'next'
import './globals.css'
import Link from 'next/link'

export const metadata: Metadata = {
    title: "Cal's cals",
    description: 'Locally produced calendars near Chalmers!',
    applicationName: "Cal's cals",
    openGraph: {
        title: "Cal's cals",
        description: 'Generated by create next app!',
        siteName: 'Olillin',
    },
    twitter: {
        title: "Cal's cals",
        description: 'Generated by create next app!',
        card: 'summary_large_image',
        site: '@olillin',
        creator: '@olillin',
    },
}

export const viewport: Viewport = {
    themeColor: '#5ac1a2',
    colorScheme: 'dark',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body className="antialiased">
                <main>
                    <section className="introduction">
                        <h1>Welcome to Cal's cals!</h1>
                        <p>
                            A better calendar experience at Chalmers, made and
                            maintained by
                            <a
                                href="https://wiki.chalmers.it/Cal"
                                target="_blank"
                            >
                                Cal
                            </a>
                            .
                        </p>
                    </section>

                    <nav>
                        <Link href={'/picker'}>Calendar picker</Link>
                        <Link href={'/builder'}>Calendar builder</Link>
                    </nav>

                    {children}
                </main>

                <footer>
                    <span>
                        Made with <span className="pixelnheart"></span> by
                        <a href="https://wiki.chalmers.it/Cal" target="_blank">
                            Cal
                        </a>
                        .
                    </span>
                    <span>
                        Is something wrong or could be improved?
                        <a
                            href="https://github.com/olillin/cals-cals/issues"
                            target="_blank"
                        >
                            Leave an issue on GitHub
                        </a>
                        !
                    </span>
                </footer>
            </body>
        </html>
    )
}
